name: Disala RDP - Ngrok 001

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1440
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile Downloads.bat
          cmd /c Downloads.bat

      - name: Connecting Ngrok Account
        run: "C:\Program Files\ngrok\ngrok.exe"  
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN_001 }}
          
      - name: Enabling RDP Access
        run: cmd /c Acess.bat 

      - name: Upload Softwares 
        run: cmd /c Uploads.bat        

      - name: Log In To Remote Desktop Protocol
        run: cmd /c start.bat

      - name: Time Count
        run: cmd /c loop.bat

