name: Disala RDP - Ngrok 001

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1400
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -OutFile Downloads.bat
          cmd /c Downloads.bat

      - name: Connecting Ngrok Account
        run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN_001 }}
          
      - name: Enabling RDP Access
        run: cmd /c Acess.bat

      - name: Upload Softwares 
        run: cmd /c Uploads.bat        

      - name: Log In To Remote Desktop Protocol
        run: cmd /c start.bat

      - name: Time Count
        run: cmd /c loop.bat
